server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IsmaelMercadoCalero/bootCamp-ConfigServer.git
        default-label: main
        search-paths:
        - '*service*'
        bootstrap: true
